apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo-configmap.yaml
  - mongo-express-deployment.yaml
  - mongo-express-service.yaml
  #- configmap.yaml


images:
  - name: mongo-express
    #newTag: 1.16-alpine
