apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-secret.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  #- configmap.yaml


images:
  - name: mongo
    #newTag: 1.16-alpine
